### ISSUE TITLE
v2.7.1 (still/again) "Item 'X' from [location] is Delayed, Missing Energy in (PLS. ILS)"

### ISSUE THREAD

**Issue by DocHogan** [mattsemar/dsp-personal-logistics#24]
#16 was, unfortunately not resolved.  As of today, the issue is actually worse. Now "Origin Planet" and "Station type" are no longer properly identified, but instead show 'Unknown'.  See pics attached.  I'm standing right next to the "Energetic Graphite" origin station, for example.

I think the 'Unknown' issue might actually be coming from CommonAPI, which also updated today, and one of the fixes was intended to fix 'unknown' issues (which I am only having SINCE the patch. Go figure)

![image](https://user-images.githubusercontent.com/8462170/151299578-56e661c6-5128-4cf4-a80d-7181ed22e30d.png)
![image](https://user-images.githubusercontent.com/8462170/151299610-6c4cd347-666a-4b4f-8720-ac6a4f8ddb9d.png)

**Comment by DocHogan** [comment]
Welllllll...maybe/maybe not. Went into Settings/Actions/Clear Requests, and the current requested items re-queued and delivered without issue. I'll close this issue and follow up if it continues. Better to tag you on discord/modding, or github issue?

**Comment by DocHogan** [comment]
Nope. But I *may* have found a possible cause. I had an unpowered ILS, set to Local Demand/Remote Supply. Powered it, cleared requests, and all is well. 

I do have powered Local Supply ILSs on this same planet. Could PL be requesting from a Local Demand/Remote Supply ILS while on the same planet, instead of a Local Supply ILS or PLS, for some reason?

EDIT/Update: Also found an unpowered copper ILS, set to Demand/Demand. Powered it, cancelled requests, and copper started flooding in. I think there's some logic broken or missing that should be gathering items from 'Supply' stations before attempting 'Demand' stations.

**Comment by mattsemar** [comment]
So, just to confirm you are set to use `IlsDemandRules`?

**Comment by DocHogan** [comment]
> So, just to confirm you are set to use `IlsDemandRules`?

Just double-checked; that is correct.

**Comment by DocHogan** [comment]
Okay, narrowed down a little bit more. Maybe. I went to the PLS as shown in pic, deleted power to station, deleted all copper in personal inventory and recycled, cleared buffer. 
![image](https://user-images.githubusercontent.com/8462170/151304824-6ec016db-4ba3-4f69-a065-1d7e46f3f96c.png)

**Comment by DocHogan** [comment]
Fuh...I don't know, now. Powered station back up, same error. I'll go do the same with all copper stations this planet.

**Comment by mattsemar** [comment]
Do you happen to have the "Never Use Mecha Energy" setting set to true?

**Comment by DocHogan** [comment]
Yes. It was absolutely destroying my energy when off-world (new planet, gas/ice giant, etc)

**Comment by mattsemar** [comment]
Ok, so it seems like there are a few things going on then. 
1. Once a station is selected to take items from, it's sort of locked in, a request like that will wait until it gets its energy cost paid basically forever. If 'Never Use Mecha Energy' is selected and the station is powered off it will just keep trying. Definitely some things I can do on this front.
2. Either I introduced a bug yesterday or the game changed with the patch this morning that causes the station and planet names not to be found (it's why you see the "from Unknown" and "in Unknown". That might actually be why after powering the station back on it didn't figure out that it could finish the delivery.

I'll see what I can do about #2, but it'll probably be the weekend before I can tackle #1 holistically. Similar to issues with warpers I think I just need to come up with a way to recover and to pay shipping costs in some other way when the supplying station can't do it (either that or kill the request before it's locked in). 

In the meantime you might want to re-enable using Mecha Energy because I think it would resolve this issue ( at least while on your home world )

**Comment by DocHogan** [comment]
It's cluster exploration time, can't give up Icarus' energy...I'll have to wait for fix :)

The 'unkown' may not be entirely on you, it may have been introduced by today's CommonAPI update that was playing with that issue.

Perhaps validate the sending station a) is a Supply station, not receive, *and* b) has power/drones/vessels, before authorized transfer. If a or b fails, cycle to next available station. If no available stations fit a+b, default to stations that succeed on at least b

**Comment by DocHogan** [comment]
It's cluster exploration time, can't give up Icarus' energy...I'll have to wait for fix :)

The 'unkown' may not be entirely on you, it may have been introduced by today's CommonAPI update that was playing with that issue.

Perhaps validate the sending station 1) has power and drones/vessels, 2) is set for Supply; before authorized transfer. If 1 *or* 2 fails, cycle to next available station. If _no_ available stations fit 1 *and* 2, default to stations that succeeds on at least #1

**Comment by mattsemar** [comment]
This should be resolved now, please open a new issue if it crops up again
