### ISSUE TITLE
ProtoRegistry is not loaded

### ISSUE THREAD

**Issue by tier1thuinfinity** [mattsemar/dsp-personal-logistics#8]
Hi mattsemar,

With the latest versions of the mod, I get the following error once I load the game and click on an ILS or PLS:
![image](https://user-images.githubusercontent.com/16158719/145054903-305e691a-fa80-44ad-b6c8-3729a8572d36.png)

Downgrading to 1.5.0 resolves the issue.

I have following mods installed:
![image](https://user-images.githubusercontent.com/16158719/145055169-a7e02d90-3b3a-45fc-a196-c95949ddad43.png)

Thanks for your hard work,
tier1thuinfinity

**Comment by mattsemar** [comment]
Shoot, not sure how that slipped by. I'll see if I can repro and push out a quick fix

**Comment by mattsemar** [comment]
Ok, I now understand how this happened, and it's somewhat interesting. It turns out that if a person has any other mod that is using ProtoRegistry correctly (mine was not) installed then this issue will be hidden. 

Thank you very much for the bug report, I would've never found this one on my own.

Also, just as an aside, you might want to consider installing BlueprintTweaks. It's a really good mod. I use it all the time since it lets you force paste blueprints and do latitude/longitudinal mirroring.

I'm closing this issue, but if version 1.6.3 does not fix the issue for you, please let me know.

**Comment by tier1thuinfinity** [comment]
Just tested the latest build and it resolves the issue. Awesome work on the quick resolution, the BlueprintTweaks recommendation, and the mod overall!

Thanks again!
